config/routes.rb
Rails.application.routes.draw do

  scope format: false do
    root 'index#index'
    post '/', to: 'index#search', as: 'search'
    get '/corporation', to: 'index#corporation', as: 'corporation'
  end

end

app/models/blueprint.rb
class Blueprint < ActiveRecord::Base

  attr_accessor :price_options, :runs, :job, :material_efficiency_percentage, :time_efficiency_percentage

  def material_efficiency
    efficiency(material_efficiency_percentage)
  end

  def time_efficiency
    efficiency(time_efficiency_percentage)
  end

  serialize :activities, Hash

  def activities=(activities)
    self[:activities] = activities.try(:deep_symbolize_keys!)
  end

  def materials
    @materials ||= activities.try(:[], :manufacturing).try(:[], :materials) || []
  end

  def materials_buy
    @materials_buy ||= materials.reduce(0) do |a, m|
      a + m[:quantity] * material_efficiency * (EveItem.get(m[:typeID]).try(:price, :materials, price_options) || 0)
    end
  end

  def products
    @products ||= activities.try(:[], :manufacturing).try(:[], :products) || []
  end

  def products_sell
    @products_sell ||= products.reduce(0) do |a, p|
      a + p[:quantity] * (EveItem.get(p[:typeID]).try(:price, :products, price_options) || 0)
    end
  end

  def products_volume
    @products_volume ||= products.reduce(0) { |a, p| a + p[:quantity] * (EveItem.get(p[:typeID]).try(:volume) || 0) }
  end

  def time
    @time ||= time_efficiency * (activities.try(:[], :manufacturing).try(:[], :time) || 0)
  end

  def per_hour(value)
    value * 3600 / time.to_f
  end

  def profit
    products_sell - materials_buy
  end

  private

  def efficiency(percentage)
    1 - (percentage || 0) / 100.to_f
  end

end

app/models/corporation.rb
class Corporation
  BLUEPRINTS = "https://api.eveonline.com/corp/Blueprints.xml.aspx?keyID=#{ENV['HUSC_API_KEY_ID']}&vCode=#{ENV['HUSC_API_VERIFICATION_CODE']}"
  JOBS = "https://api.eveonline.com/corp/IndustryJobs.xml.aspx?keyID=#{ENV['HUSC_API_KEY_ID']}&vCode=#{ENV['HUSC_API_VERIFICATION_CODE']}"

  def self.blueprints
    jobs = fetch(JOBS).map { |j| j[:blueprintID] }
    fetch(BLUEPRINTS).map do |row|
      b = to_blueprint(row)
      b.job = jobs.include? row[:itemID]
      b
    end
  end

  private

  class << self
    def to_blueprint(row)
      blueprint = Blueprint.find_by(type_id: row[:typeID])
      blueprint.material_efficiency_percentage = row[:materialEfficiency].to_i
      blueprint.time_efficiency_percentage = row[:timeEfficiency].to_i
      blueprint.runs = row[:runs].to_i
      blueprint
    end

    def fetch(url)
      Hash.from_xml(RestClient.get(url)).deep_symbolize_keys[:eveapi][:result][:rowset][:row]
    end
  end
end

app/models/eve_central_price.rb
class EveCentralPrice
  def self.get(type_id, options)
    prices = Rails.cache.fetch "eve-central/#{options[:system]}/#{type_id}", expires_in: 8.hours do
      JSON.parse(RestClient.get "#{Rails.configuration.eve_central}?typeid=#{type_id}&usesystem=#{options[:system]}").first.deep_symbolize_keys!
    end
    {
        materials: prices[options[:materials_order].to_sym][options[:materials].to_sym],
        products: prices[options[:products_order].to_sym][options[:products].to_sym]
    }
  end
end

app/models/eve_item.rb
class EveItem < ActiveRecord::Base
  def self.get(type_id)
    self.find_by type_id: type_id
  end

  def price(type=nil, options=nil)
    begin
      raise unless type && options
      EveCentralPrice.get(type_id, options)[type]
    rescue
      read_attribute :price
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  include PriceHelper

  LIMIT = 50

  def index
  end

  def search
    @value = params[:value]
    results = search_by(@value)
    flash[:notice] = "Too many blueprints, showing first #{LIMIT}" if results.size > LIMIT
    @blueprints = out(results[0..LIMIT-1])
    render :index
  end

  def corporation
    @blueprints = out(Corporation.blueprints)
    render :index
  end

  private

  def search_by(query)
    query
        .lines
        .map { |l| l.strip.split("\t").first }
        .compact
        .map { |l| EveItem.where(name: "#{l.gsub(/ Blueprint/, '')} Blueprint").to_a }
        .flatten
        .map { |i| Blueprint.find_by(type_id: i.type_id) }
        .uniq
  end

  def out(blueprints)
    blueprints
        .each { |b| b.price_options = price_options }
        .sort_by { |b| -b.per_hour(b.profit) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def available_systems
    options_for_select [
                           ['Amarr', 30002187],
                           ['Jita', 30000142],
                           ['Dodixie', 30002659],
                           ['Rens', 30002510],
                           ['Hek', 30002053],
                           ['Teonusude', 30002385],
                           ['Sasta', 30000005],
                       ], 30002187
  end

  def available_prices(type)
    options_for_select [
                           %w(Min min),
                           %w(Max max),
                           %w(Median median),
                           %w(Average avg),
                       ], {materials: 'max', products: 'min'}[type]
  end
end

app/helpers/index_helper.rb
module IndexHelper
  def example_search
    [
        "Carbonized Lead S Blueprint	1	Projectile Ammo Blueprint			0,01 m3",
        "Proton S Blueprint	1	Projectile Ammo Blueprint			0,01 m3",
        "Warrior II Blueprint",
        "Vexor",
    ].join "\n"
  end
end

app/helpers/price_helper.rb
module PriceHelper
  def price_options
    {
        system: cookies['system'],
        materials: cookies['materials'],
        products: cookies['products'],
        materials_order: cookies['materials-order'],
        products_order: cookies['products-order'],
    }
  end
end

app/views/index/index.html.erb
<% content_for(:body_attributes) do %>data-no-turbolink="true"<% end %>
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-block">
        <%= form_tag search_path do %>
            <%= text_area_tag :value, @value || example_search, class: 'form-control', style: 'height: 85px;' %>
            <div class="m-t-1">
              <%= submit_tag 'Search', class: 'btn btn-primary' %>
              <%= link_to 'Corporation', corporation_path, class: 'btn btn-primary pull-xs-right' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-block">
        <form id="pricing" class="m-l-1">
          <div class="form-group row">
            <label class="col-sm-2 form-control-label" for="system">System</label>
            <div class="col-sm-10"><%= select_tag :system, available_systems, class: 'c-select' %></div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 form-control-label" for="materials">Materials</label>
            <div class="col-sm-10">
              <%= select_tag :materials, available_prices(:materials), class: 'c-select m-r-2' %>
              <label class="radio-inline form-control-label">
                <%= radio_button_tag 'materials-order', :buy, true %> Buy order
              </label>
              <label class="radio-inline form-control-label">
                <%= radio_button_tag 'materials-order', :sell %> Sell order
              </label>
            </div>
          </div>
          <div class="form-group row m-b-0">
            <label class="col-sm-2 form-control-label" for="products">Products</label>
            <div class="col-sm-10">
              <%= select_tag :products, available_prices(:products), class: 'c-select m-r-2' %>
              <label class="radio-inline form-control-label">
                <%= radio_button_tag 'products-order', :buy %> Buy order
              </label>
              <label class="radio-inline form-control-label">
                <%= radio_button_tag 'products-order', :sell, true %> Sell order
              </label>
            </div>
          </div>
        </form>

      </div>
    </div>
  </div>
</div>

<% if @blueprints %>
    <div class="card">
      <div class="card-block">
        <h3 class="card-title">Blueprints</h3>
        <table id="blueprints" class="table table-hover table-sm m-b-0">
          <thead>
          <tr>
            <th>#</th>
            <th colspan="2">Name</th>
            <th class="text-muted">Time</th>
            <th class="text-xs-right text-muted">Volume</th>
            <th class="text-xs-right" colspan="2">Material cost</th>
            <th class="text-xs-right" colspan="2">Price</th>
            <th class="text-xs-right">Profit</th>
          </tr>
          </thead>
          <% @blueprints.each_with_index do |b, i| %>

              <tbody class="blueprint<%= ' has-job' if b.job %>" data-i="<%= i %>">
              <tr data-type-id="<%= b.products.map { |p| p[:typeID] }.join ',' %>">
                <td>
                  <% if b.runs == -1 %>
                      <span class="label label-default">Original</span>
                  <% elsif b.runs %>
                      <span class="label label-success"><%= b.runs %> runs</span>
                  <% end %>
                </td>
                <td><%= b.products.map { |p| "#{p[:quantity]} x #{EveItem.get(p[:typeID]).try :name}" }.join %></td>
                <td class="mono text-xs-right">
                  <% if b.time_efficiency_percentage && b.time_efficiency_percentage > 0 %>
                      <span class="label label-default"><%= number_to_percentage(b.time_efficiency_percentage, precision: 0) %></span>
                  <% end %>
                </td>
                <td class="text-muted"><%= distance_of_time_in_words b.time %></td>
                <td class="mono text-xs-right text-muted" data-toggle="tooltip" data-placement="right" data-offset="0px 5px"
                    title="<%= number_with_precision(b.per_hour(b.products_volume), precision: 2) %> m³ / h">
                  <%= number_with_precision(b.products_volume, precision: 2) %> m³
                </td>
                <td class="mono">
                  <% if b.material_efficiency_percentage && b.material_efficiency_percentage > 0 %>
                      <span class="label label-primary"><%= number_to_percentage(b.material_efficiency_percentage, precision: 0) %></span>
                  <% end %>
                </td>
                <td class="mono text-xs-right"><%= number_to_currency(b.materials_buy) %></td>
                <td class="mono text-xs-right" colspan="2"><%= number_to_currency(b.products_sell) %></td>
                <td class="mono text-xs-right" data-toggle="tooltip" data-placement="left" data-offset="0px -10px"
                    title="<%= number_to_currency(b.per_hour b.profit) %> / h">
                  <%= number_to_currency(b.profit) %>
                </td>
              </tr>
              </tbody>

              <tbody class="materials hidden<%= ' has-job' if b.job %>" data-i="<%= i %>" data-i="<%= i %>">
              <% b.materials.each do |m| %>
                  <tr data-type-id="<%= m[:typeID] %>">
                    <% eve_item = EveItem.get(m[:typeID]) %>
                    <% price = EveItem.get(m[:typeID]).try(:price, :materials, price_options) %>
                    <% quantity = m[:quantity] %>
                    <td></td>
                    <td colspan="3"><%= quantity %> x <%= eve_item.try :name %></td>
                    <td class="mono text-xs-right text-muted" data-toggle="tooltip" data-placement="right"
                        title="<%= eve_item ? number_with_precision(b.per_hour(quantity * eve_item.volume), precision: 2) : '-' %> m³ / h">
                      <%= eve_item ? number_with_precision(quantity * eve_item.volume, precision: 2) : '-' %> m³
                    </td>
                    <td class="mono text-xs-right" colspan="2"><%= price ? number_to_currency(quantity * price) : '-' %></td>
                    <td class="mono">= <%= quantity %> x</td>
                    <td class="mono text-xs-right text-market"><%= number_to_currency(price) %></td>
                    <td></td>
                  </tr>
              <% end %>
              </tbody>

          <% end %>
        </table>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HUS-C</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= controller_name %>" data-locale="<%= I18n.locale %>" <%= yield(:body_attributes) if content_for?(:body_attributes) %>>

<nav class="navbar navbar-fixed-top">
  <a class="navbar-brand" href="/">HUS-C</a>
</nav>

<div class="container-fluid">
  <% if notice %>
      <div class="alert alert-warning" id="notice"><%= notice %></div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>